# Generated by Django 6.0.7 on 2026-09-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COUNSELLOR', 'Counsellor'), ('STORE_MANAGER', 'Store Manager')], default='ADMIN', max_length=20),
        ),
    ]
