# Generated by Django 6.0.7 on 2026-09-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='baseline_notes',
            field=models.TextField(blank=True, help_text='Known baseline behaviour or routine used for comparison.'),
        ),
        migrations.AddField(
            model_name='patient',
            name='care_focus',
            field=models.TextField(blank=True, help_text='Relevant care or observation focus for this patient.'),
        ),
        migrations.AddField(
            model_name='patient',
            name='observation_focus',
            field=models.TextField(blank=True, help_text='Specific behaviours or factors counsellors should observe.'),
        ),
    ]
