# Generated by Django 6.0.7 on 2026-10-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_baseline_notes_patient_care_focus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='known_conditions',
            field=models.TextField(blank=True, help_text='Documented condition(s) provided by authorized clinical or care staff. This field is not generated by AI.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_focus',
            field=models.TextField(blank=True, help_text='Relevant care or support focus for this patient.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, help_text='Patient description related to the documented condition(s). Do not use this field for AI diagnosis.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='observation_focus',
            field=models.TextField(blank=True, help_text='Specific behaviours or factors counsellors should observe during routine interactions.'),
        ),
    ]
