# Generated by Django 6.0.7 on 2026-07-28 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('CALM', 'Calm'), ('SAD', 'Sad'), ('AGGRESSIVE', 'Aggressive')], max_length=15)),
                ('behaviour', models.CharField(choices=[('COOPERATIVE', 'Cooperative'), ('WITHDRAWN', 'Withdrawn'), ('RESTLESS', 'Restless'), ('DISRUPTIVE', 'Disruptive')], max_length=15)),
                ('sleep_quality', models.CharField(choices=[('GOOD', 'Good'), ('POOR', 'Poor')], max_length=5)),
                ('appetite', models.CharField(choices=[('GOOD', 'Good'), ('POOR', 'Poor')], max_length=5)),
                ('personal_hygiene', models.CharField(choices=[('GOOD', 'Good'), ('POOR', 'Poor')], max_length=5)),
                ('communication', models.CharField(choices=[('NORMAL', 'Normal'), ('LIMITED', 'Limited'), ('NONE', 'None')], max_length=10)),
                ('participation', models.CharField(choices=[('ACTIVE', 'Active'), ('REFUSED', 'Refused')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('poi_score', models.PositiveIntegerField(default=0, editable=False)),
                ('priority_level', models.CharField(choices=[('STABLE', 'Stable'), ('NEEDS_OBSERVATION', 'Needs Observation'), ('NEEDS_ATTENTION', 'Needs Attention'), ('HIGH_PRIORITY', 'High Priority')], default='STABLE', editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations_made', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='patient.patient')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'unique_together': {('patient', 'date', 'time')},
            },
        ),
    ]
