# Generated by Django 6.0.7 on 2026-08-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(blank=True)),
                ('journal', models.CharField(blank=True, max_length=300)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('paper_url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('dataset_name', models.CharField(blank=True, max_length=300)),
                ('key_finding', models.TextField()),
                ('source', models.CharField(default='IEEE', max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('source_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=300)),
                ('related_papers', models.ManyToManyField(blank=True, related_name='datasets', to='evidence.researchpaper')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('observation_fields', models.JSONField(default=list)),
                ('pattern_description', models.TextField()),
                ('possible_concern', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('minimum_days', models.PositiveIntegerField(default=7)),
                ('active', models.BooleanField(default=True)),
                ('supporting_papers', models.ManyToManyField(blank=True, related_name='observation_patterns', to='evidence.researchpaper')),
            ],
        ),
    ]
