# Generated by Django 6.0.7 on 2026-08-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationpattern',
            name='minimum_occurrences',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of observations that must match each pattern condition.'),
        ),
    ]
