# Generated by Django 6.0.7 on 2026-09-21 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_observationpattern_minimum_occurrences'),
        ('patient', '0002_patient_baseline_notes_patient_care_focus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('observation_days', models.PositiveIntegerField(default=0)),
                ('matched_pattern', models.CharField(blank=True, max_length=255)),
                ('observation_summary', models.TextField()),
                ('observed_changes', models.JSONField(default=list)),
                ('evidence_interpretation', models.TextField(blank=True)),
                ('recommended_follow_up', models.TextField(blank=True)),
                ('disclaimer', models.TextField(blank=True)),
                ('research_evidence', models.JSONField(default=list)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_ai_summaries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary_history', to='patient.patient')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
