# Generated by Django 6.0.7 on 2026-10-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_aisummaryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummaryhistory',
            name='structured_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='observationpattern',
            name='minimum_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
